# Generated by Django 5.0.6 on 2024-09-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants_app', '0002_add_User'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisine_types',
            new_name='cuisine_type',
        ),
    ]
